### PR TITLE
Increase default timeout to 60 seconds

### LINKED ISSUE #84: Refreshing bitcoin UTXO sometimes times out and we receive a ESOCKETTIMEOUT exception
We should investigate why updating the UTXO set times out randomly. 

`#033[39mFailed to refresh UTXO: ESOCKETTIMEDOUT" `

related to these lines: 
https://github.com/coblox/bobtimus/blob/af6ff678f9555561e86a9540ae8bd4dcf9d067c1/src/index.ts#L23-L30

and 
https://github.com/coblox/bobtimus/blob/af6ff678f9555561e86a9540ae8bd4dcf9d067c1/src/wallets/bitcoin.ts#L150-L177

Additional information:
- Currently, we just hold on to the initial request that triggers the scan. `bitcoind` provides a way of checking for the status of the scan and later extract the result, however we don't know how to do that exactly. Check bitcoind documentation.
- It looks like we can't configure the timeout atm. Could be worth ditching the library we are using because it doesn't add much value.

### PR DESCRIPTION
**Pull request by bonomat**
This PR increases the default timeout of the bitcoind rpc client to 60 seconds. I opted for no config file to keep the configuration overhead to a minimum. 

Resolves #84

### CODE REVIEW

File: src/bitcoin/bitcoinCoreRpc.ts [hunk 1]
```diff
@@ -68,7 +68,8 @@ export class BitcoinCoreRpc implements BitcoinBlockchain {
       username,
       password,
       host,
-      port
+      port,
+      timeout: 60000
```
Comment (tcharding) [inline src/bitcoin/bitcoinCoreRpc.ts]: Can we have a const instead of a magic number please (with an comment on how the value was chosen).  Thanks

Comment (bonomat) [reply src/bitcoin/bitcoinCoreRpc.ts]: I think inline is fine as this value is only used in here and it should not change. 
Also, there is no scientific reason behind this value besides: _just increase it, deploy it_ and see if it reduces the timeouts :D
